### PR TITLE
ANY23-447 : Excluded unnecessary dependencies.

### PR DESCRIPTION
**Pull request by asutosh936**

### CODE REVIEW

**Comment by asutosh936** [comment]
@lewismc - Reduced bloating dependencies.

**Comment by HansBrende** [comment]
@asutosh936 I'm pretty sure ANY23-447 didn't concern any23-server.

**Comment by lewismc** [comment]
Hi @asutosh936 thank you for the pull request.
I'm not sure about this one... I know that Tika makes Any23 heavy and I think we should try to avoid this at all costs.
However, we do for example require SnakeYAML as it is used within one of the core extractors.

**Comment by lewismc** [comment]
Hi @asutosh936 I can't merge this PR in it's current condition. Throwing ClassNotFoundExceptions all the time is not acceptable. I have attached the result of `mvn dependency:analyze` to https://issues.apache.org/jira/projects/ANY23/issues/ANY23-447 if you are interested in looking.

**Pull request closed without merging**
